set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H5 [get_ports {led[0]}]
set_property PACKAGE_PIN J5 [get_ports {led[1]}]
set_property PACKAGE_PIN T9 [get_ports {led[2]}]
set_property PACKAGE_PIN T10 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[3]}]
#set_property PACKAGE_PIN F6 [get_ports {gpio[0]}]
#set_property PACKAGE_PIN J4 [get_ports {gpio[1]}]
#set_property PACKAGE_PIN J2 [get_ports {gpio[2]}]
#set_property PACKAGE_PIN H6 [get_ports {gpio[3]}]

set_property PACKAGE_PIN G13 [get_ports {gpio[0]}]
set_property PACKAGE_PIN B11 [get_ports {gpio[1]}]
set_property PACKAGE_PIN A11 [get_ports {gpio[2]}]
set_property PACKAGE_PIN D12 [get_ports {gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_csno[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports spi_sck_o]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sdi_i]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sdo_o]
set_property IOSTANDARD LVCMOS33 [get_ports twi_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports twi_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_rxd_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart0_txd_o]

#Set to Flash
set_property PACKAGE_PIN L16 [get_ports spi_sck_o]
set_property PACKAGE_PIN K17 [get_ports spi_sdi_i]
set_property PACKAGE_PIN K18 [get_ports spi_sdo_o]
set_property PACKAGE_PIN L13 [get_ports {spi_csno[0]}]

set_property PACKAGE_PIN L18 [get_ports twi_scl_io]
set_property PACKAGE_PIN M18 [get_ports twi_sda_io]
set_property PACKAGE_PIN D10 [get_ports uart0_txd_o]
set_property PACKAGE_PIN A9 [get_ports uart0_rxd_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart1_rxd_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart1_txd_o]
set_property PACKAGE_PIN U16 [get_ports uart1_txd_o]
set_property PACKAGE_PIN V15 [get_ports uart1_rxd_i]

#set_property IOSTANDARD LVCMOS33 [get_ports pwm_o_n]
#set_property PACKAGE_PIN C5 [get_ports pwm_o_n] # a0
#set_property IOSTANDARD LVCMOS33 [get_ports pwm_o_p]
#set_property PACKAGE_PIN C6 [get_ports pwm_o_p] #a0

##set_property PACKAGE_PIN F1 [get_ports spi_sck_o]
##set_property PACKAGE_PIN G1 [get_ports spi_sdi_i]
##set_property PACKAGE_PIN H1 [get_ports spi_sdo_o]
##set_property PACKAGE_PIN C1 [get_ports {spi_csno[0]}]